-- drop table USER_LOAD_BREAK_TEST1;

create table USER_LOAD_BREAK_TEST1 AS
SELECT
    *
FROM USER_LOAD_BREAK;

drop table USER_LOAD_BREAK_TEST2;
create table USER_LOAD_BREAK_TEST2 AS
SELECT
    *
FROM USER_LOAD_BREAK;

drop table USER_LOAD_BREAK_TEST3;
create table USER_LOAD_BREAK_TEST3 AS
SELECT
    *
FROM USER_LOAD_BREAK;

